runtime: python39
entrypoint: gunicorn -b :$PORT app:app

instance_class: F1  # Low-cost instance

env_variables:
  DB_USER: "appuser"
  DB_PASS: "app@123"
  DB_NAME: "weather_db"
  INSTANCE_CONNECTION_NAME: "weather-app-455714:asia-south1:weather-db"

handlers:
- url: /.*
  script: auto
  secure: always
